# Generated by Django 5.1.1 on 2024-09-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_bid_bidder_name_bid_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='farmer',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Escrow',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
