# Generated by Django 5.1.1 on 2024-09-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='farmer addr'),
            preserve_default=False,
        ),
    ]
