# Generated by Django 5.1.1 on 2024-09-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_userprofile_city_remove_userprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crops',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
